name: challenge_google_design_system
repository: https://github.com/fluttely/challenge_google_design_system

packages:
  - apps/google_drive/
  - apps/google_keep/
  - apps/google_mail/
  - packages/google_core/
  - packages/google_design_system/

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  get:
    name: Get dependencies for all packages
    run: melos bootstrap

  clean:
    name: Clean all packages
    run: melos clean

  analyze:
    name: Analyze all packages
    run: melos exec -- "flutter analyze"

  format:
    name: Format all packages
    run: melos exec -- "dart format lib/ test/"
