name: google_core
description: Core models and utilities shared across Google apps
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_design_system:
    path: ../google_design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
