include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  exclude:
    - build/**
    - lib/src/core/presentation/i18n/**
    - "**/*.g.dart"
    - lib/generated_plugin_registrant.dart
    - lib/firebase_options_dev.dart
    - lib/firebase_options_prod.dart
  errors:
    constant_identifier_names: ignore
    invalid_annotation_target: ignore
